
export let emailArray = [
    {
      id: 1,
      to: "Me",
      from: "John Smith",
      date: "5 Dec 2016 15:00",
      subject: "Hello There asd asd asddQ fasd fasdf",
      body: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus dignissimos magnam pariatur adipisci ex unde laboriosam blanditiis harum, </p><p>quas accusamus eveniet saepe, molestiae quam eum ipsum sit <strong>quisquam</strong> veniam autem. Debitis excepturi quos ex dolor, laudantium repellat inventore voluptatibus saepe libero repudiandae sint. Eveniet corporis sed, cum alias enim illo!</p>",
      isRead: false,
      folder: "inbox",
    },
    {
      id: 2,
      to: "Me, John Smith",
      from: "Jane Francis",
      date: "5 Dec 2016 14:20",
      subject: "Some Info",
      body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus dignissimos magnam pariatur adipisci ex unde laboriosam blanditiis harum, quas accusamus eveniet saepe, molestiae quam eum ipsum sit quisquam veniam autem. Debitis excepturi quos ex dolor, laudantium repellat inventore voluptatibus saepe libero repudiandae sint. Eveniet corporis sed, cum alias enim illo!<br><br>Jane",
      isRead: false,
      folder: "inbox",
    },
    {
      id: 3,
      to: "Me",
      from: "OKProducts Inc",
      date: "4 Dec 2016 11:12",
      subject: "New!! Much Value! 99% off!",
      body: "<a href='#'>Click here to win!</a>",
      isRead: false,
      folder: "inbox",
    },
    {
      id: 4,
      to: "Me",
      from: "OKProducts Inc",
      date: "4 Dec 2016 11:12",
      subject: "New!! Much Value! 99% off!",
      body: "<a href='#'>Click here to win!</a>",
      isRead: false,
      folder: "inbox",
    },
    {
        id: 5,
        to: "Me",
        from: "John Smith",
        date: "5 Dec 2016 15:00",
        subject: "Hello There asd asd asddQ fasd fasdf",
        body: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus dignissimos magnam pariatur adipisci ex unde laboriosam blanditiis harum, </p><p>quas accusamus eveniet saepe, molestiae quam eum ipsum sit <strong>quisquam</strong> veniam autem. Debitis excepturi quos ex dolor, laudantium repellat inventore voluptatibus saepe libero repudiandae sint. Eveniet corporis sed, cum alias enim illo!</p>",
        isRead: false,
        folder: "inbox",
      },
      {
        id: 6,
        to: "Me",
        from: "John Smith",
        date: "5 Dec 2016 15:00",
        subject: "Hello There asd asd asddQ fasd fasdf",
        body: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus dignissimos magnam pariatur adipisci ex unde laboriosam blanditiis harum, </p><p>quas accusamus eveniet saepe, molestiae quam eum ipsum sit <strong>quisquam</strong> veniam autem. Debitis excepturi quos ex dolor, laudantium repellat inventore voluptatibus saepe libero repudiandae sint. Eveniet corporis sed, cum alias enim illo!</p>",
        isRead: false,
        folder: "inbox",
      },
      {
        id: 7,
        to: "Me",
        from: "John Smith",
        date: "5 Dec 2016 15:00",
        subject: "Hello There asd asd asddQ fasd fasdf",
        body: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus dignissimos magnam pariatur adipisci ex unde laboriosam blanditiis harum, </p><p>quas accusamus eveniet saepe, molestiae quam eum ipsum sit <strong>quisquam</strong> veniam autem. Debitis excepturi quos ex dolor, laudantium repellat inventore voluptatibus saepe libero repudiandae sint. Eveniet corporis sed, cum alias enim illo!</p>",
        isRead: false,
        folder: "sent",
      },
      {
        id: 8,
        to: "Me",
        from: "John Smith",
        date: "5 Dec 2016 15:00",
        subject: "Hello There asd asd asddQ fasd fasdf",
        body: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus dignissimos magnam pariatur adipisci ex unde laboriosam blanditiis harum, </p><p>quas accusamus eveniet saepe, molestiae quam eum ipsum sit <strong>quisquam</strong> veniam autem. Debitis excepturi quos ex dolor, laudantium repellat inventore voluptatibus saepe libero repudiandae sint. Eveniet corporis sed, cum alias enim illo!</p>",
        isRead: false,
        folder: "sent",
      },
      {
        id: 9,
        to: "Me",
        from: "John Smith",
        date: "5 Dec 2016 15:00",
        subject: "Hello There asd asd asddQ fasd fasdf",
        body: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus dignissimos magnam pariatur adipisci ex unde laboriosam blanditiis harum, </p><p>quas accusamus eveniet saepe, molestiae quam eum ipsum sit <strong>quisquam</strong> veniam autem. Debitis excepturi quos ex dolor, laudantium repellat inventore voluptatibus saepe libero repudiandae sint. Eveniet corporis sed, cum alias enim illo!</p>",
        isRead: false,
        folder: "inbox",
      },
  ];
